Erails/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
] 
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

app/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 

urlpatterns = [
    path('',views.index),
    path('productview/<int:pk>', views.productView,name='productview'),
]

app/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    category_name = models.CharField(max_length=20)

    def __str__(self):
        return self.category_name


class Products(models.Model):
    product_code = models.CharField(max_length=20)
    product_name = models.CharField(max_length=20)
    product_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_image = models.ImageField(upload_to='images/',null=True, blank=True)
    product_description = models.CharField(max_length=2000)

    def __str__(self):
        return self.product_name

class ProductImage(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/',null=True, blank=True)

    def __str__(self):
        return self.product.product_name

app/views.py
from django.shortcuts import render
from . models import Products
# Create your views here.

def index(request):
    obj=Products.objects.all()
    return render(request,"index.html",{"obj":obj})

def productView(request,pk):
    obj=Products.objects.filter(id=pk)
    return render(request,"productview.html",{"obj":obj})

app/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="">
<head>
<title>{% block title %} This is Base {% endblock %}</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="{% static 'layout/styles/layout.css' %}" rel="stylesheet" type="text/css" media="all">
<link href="{% static 'layout/styles/style.css' %}" rel="stylesheet" type="text/css" media="all">
<link href="{% static 'layout/styles/style2.css' %}" rel="stylesheet" type="text/css" media="all">


</head>
<body id="top">

  <header >
    
    <div class="header-1">
    
      <a href="index.html"><img style="width: 50%;" src="{% static 'images/logo_2.png' %}" /></a></li>
    
        <div class="form-container">
            <form action="">
                <input type="search" placeholder="search products" id="search" /> 
                <label for="search" class="fas fa-search"></label>
            </form>
        </div>
    
    </div>
    
    <div class="header-2">
    
        <div id="menu" class="fas fa-bars"></div>
    
        <nav class="navbar">
            <ul>
                <li><a class="active" href="#home">home</a></li>
                <li><a href="#arrival">Products</a></li>
                <li><a href="#featured">Services</a></li>
                <li><a href="#gallery">About Us</a></li>
                <li><a href="#deal">Contact Us</a></li>
            </ul>
        </nav>
    
        <div class="icons">
            <a href="#" class="fas fa-heart"></a>
            <a href="#" class="fas fa-shopping-cart"></a>
            <a href="#" class="fas fa-user"></a>
        </div>
    
    </div>
    
    </header>
    
    


  {% block body %}
  
  
{% endblock %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script language="JavaScript" type="text/javascript" src="{% static 'layout/script.js' %}"></script>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% block title %}Home Page{% endblock %}
{% block body %}
<section class="carousel">
  <div class="carousel__container">
    
    <center style="margin-bottom: 50px; font-size: 20px;">Category</center>

    {% for data in obj %}
    <div class="carousel-item">
     <a href="/productview/{{data.id}}"> <img class="carousel-item__img" src="{{data.product_image.url}}"> </a>
      <div class="panel1">
        <a href="#" class="far fa-bookmark"></a>
      </div>
      <div class="info">
        <br><br>
        <div >
          <b> {{data.product_name}} </b>
        </div >
        <br>
        <p >Product Code: {{data.product_code}}</p>
      </div>
    </div>
    {% endfor %}
  </div>
</section>

{% endblock %}

app/templates/productview.html
{% extends 'base.html' %}
{% block title %}Home Page{% endblock %}
{% block body %}

<div class = "card-wrapper">
  <div class = "card">
    <!-- card left -->
    <div class = "product-imgs">
      <div class = "img-display">
        <div class = "img-showcase">
          {% for data in obj %}
          <img src = "{{data.product_image.url}}" alt = "shoe image" id="imagebox">
          {% endfor %}
        </div>
      </div>
      <div class = "img-select">
        {% for data in obj %}
        <div class = "img-item">
            <img src = "{{data.product_image.url}}" alt = "shoe image" onclick="clickme(this)">
        </div>
        {% for data1 in data.productimage_set.all %}
        <div class = "img-item">
            <img src = "{{data1.image.url}}" alt = "shoe image" onclick="clickme(this)">
        </div>
        {% endfor %}
          {% endfor %}
      </div>
    </div>
    <!-- card right -->
    {% for data in obj %}
    <div class = "product-content">
     <h2 class = "product-title">{{data.product_name}}</h2>
      <a href = "#" class = "product-link">Product Code : {{data.product_code}}</a>
      

      <div class = "product-price">
        <p class = "new-price">New Price: <span>$249.00 (5%)</span></p>
      </div>

      <div class = "product-detail">
        <h2>about this item: </h2>
        <p>{{data.product_description}}</p>
        <ul>
          <li>Color: <span>Black</span></li>
          <li>Available: <span>in stock</span></li>
          <li>Category: <span>{{data.product_category}}</span></li>
          <li>Shipping Area: <span>Karnataka</span></li>
          <li>Shipping Fee: <span class = "new-price">$300.00 (5%)</span></li>
        </ul>
      </div>
      {% endfor %}
      <div class = "purchase-info">
        <input type = "number" min = "0" value = "1">
        <button type = "button" class = "btn">
          Ask Price <i class = "fas fa-shopping-cart"></i>
        </button>
        <button type = "button" class = "btn">Order</button>
      </div>

      
    </div>
  </div>
</div>


{% endblock %}